#ifndef PROJECT_TEST_SUPPORT_MPU_WRAPPERS_H
#define PROJECT_TEST_SUPPORT_MPU_WRAPPERS_H

#define PRIVILEGED_FUNCTION
#define PRIVILEGED_DATA
#define FREERTOS_SYSTEM_CALL
#define portUSING_MPU_WRAPPERS 0

#endif